### ISSUE TITLE
Missing account info

### ISSUE THREAD

**Issue by gustofinance** [moshthepitt/flm-jupiter-arb#1]
When running a simple jupitor arb, it seems to be getting hung up on different pools where it's saying that the account info is missing. any insight into this? 

Error: Account info 5NLeMabMyuJQUbvXNfVyUPbtYKwTXBesfmFmDswbgqUz missing

**Comment by gustofinance** [comment]
![Screen Shot 2023-01-24 at 12 25 25 PM](https://user-images.githubusercontent.com/98982076/214402035-9bc71a9e-021f-498c-a22a-9d5b51b8d8b8.png)

**Comment by moshthepitt** [comment]
`5NLeMabMyuJQUbvXNfVyUPbtYKwTXBesfmFmDswbgqUz` seems to be a Raydium AMM account, and this error is coming from deep inside Jupiter core logic so I am not sure if there's a lot we can do about it.  But will research a bit to see.
